WIP Cap certificate download to 64KB
signalwire/libstirshaken pull request #115
Opened 2021-11-16 23:14 UTC by crienzo

2021-11-16 23:18 UTC, andywolk requested changes

2021-11-16 23:18 UTC, andywolk commented on src/stir_shaken_service.c
> +		printf("WTF Exceeded max HTTP(s) download size");
Do we really need to say `WTF` here?

2021-11-16 23:22 UTC, crienzo commented on src/stir_shaken_service.c
> +		printf("WTF Exceeded max HTTP(s) download size");
no :)

2021-11-16 23:28 UTC, andywolk approved these changes

2021-11-17 19:07 UTC, crienzo commented
@andywolk this is all set

2021-11-17 19:07 UTC, crienzo commented
@andywolk this is all set

2021-11-17 19:07 UTC, crienzo commented
Squash when merging, please

2021-11-17 19:22 UTC, merged