Add support to read and write certificates with chain certificates
signalwire/libstirshaken pull request #124
Opened 2022-11-30 09:06 UTC by mrtrev

This will allow the libstirshaken library to read and write files containing the chain certificates required by some certificates in order to pass validation.  The new functionality has been implemented as such that existing applications will not break and may test for support of these new functions.

These changes are confirmed working in a production environment.

2022-12-20 16:17 UTC, mrtrev commented on src/stir_shaken_ssl.c
> +        goto fail;
Yes we can do that.  New commit incoming in a moment.

2022-12-20 16:27 UTC, andywolk commented
> Unit-tests failed: https://public-artifacts.signalwire.cloud/drone/signalwire/libstirshaken/28/artifacts.html

This PR contains changes from another PR. Please use the branch of the other PR here. Not master.

2022-12-20 16:33 UTC, mrtrev commented
Sorry I'm not used to the github workflow.  I'm not sure how to remedy this... I don't think I can change the branch the PR is from.  Should I revert the change and force push this branch or do I need to create a whole new PR from a different branch and close this one?

2022-12-20 16:50 UTC, mrtrev commented
Ok I think it is sorted out and back to a coherent PR.

2023-01-16 23:52 UTC, andywolk requested changes

2023-01-16 23:52 UTC, andywolk commented on src/stir_shaken_ssl.c
> +		goto fail;
Please fix formatting. This is because tabs are mixed with spaces.

2023-01-16 23:52 UTC, andywolk commented on src/stir_shaken_ssl.c
> +    int w = 0;
Declaring a new var could be avoided.

2023-01-16 23:52 UTC, andywolk commented on src/stir_shaken_ssl.c
> +            w = PEM_write_X509(fp, xc);
`if (!PEM_write_X509(fp, xc))` ?

2023-01-16 23:52 UTC, andywolk commented on src/stir_shaken_ssl.c
> +            xc = sk_X509_value(xchain, i);
`if (!sk_X509_value(xchain, i)) continue;` ?

2023-01-17 01:19 UTC, mrtrev commented on src/stir_shaken_ssl.c
> +		goto fail;
Done.  Looks like a copy/paste victim from elsewhere in the code (noticed lots of tab/space inconsistencies).

2023-01-17 01:20 UTC, mrtrev commented on src/stir_shaken_ssl.c
> +            xc = sk_X509_value(xchain, i);
xc holds the certificate, this one is needed for the following function if the call was successful.

2023-01-17 10:02 UTC, andywolk requested changes

2023-01-17 10:02 UTC, andywolk commented on src/stir_shaken_ssl.c
> +            xc = sk_X509_value(xchain, i);
Sure. I wanted to say `if (!(sc = sk_X509_value(xchain, i))) continue;` like the other ones. Looks clearer.

2023-01-17 16:10 UTC, mrtrev commented on src/stir_shaken_ssl.c
> +	}
I've gone ahead and just reflowed the whole file so it no longer contains any tabs.  My editor would see them and assume we're using tabs for formatting.  This should help everyone going forward.

2023-01-17 16:46 UTC, andywolk commented
@mrtrev Let's not create huge commits changing spacing in the whole codebase. Please remove it and fix what we touch only.

2023-01-17 16:58 UTC, andywolk requested changes

2023-01-17 16:58 UTC, andywolk commented on src/stir_shaken_ssl.c
> +            if (PEM_write_X509(fp, xc)) continue;
Why continue? This looks unusual even if that's correct.
May be just
```
if (!PEM_write_X509(fp, xc)) {
            snprintf(err_buf, sizeof(err_buf), "Error writing certificate chain to file %s", cert_full_name);
            stir_shaken_set_error(ss, err_buf, STIR_SHAKEN_ERROR_FILE_WRITE_2);
            goto fail;
}
```

2023-01-17 17:04 UTC, mrtrev commented on src/stir_shaken_ssl.c
> +            if (PEM_write_X509(fp, xc)) continue;
done

2023-01-17 21:18 UTC, andywolk approved these changes

2023-01-17 21:19 UTC, andywolk commented
Ok. Looks good to me.
@mrtrev Does it still work? And let's merge if so.

2023-01-17 21:52 UTC, mrtrev commented
It still compiles.  I'll put it in prod and will advise tomorrow if nothing abnormal observed.

2023-01-18 18:14 UTC, merged